### ISSUE TITLE
Crash on NULLable PostgreSQL bytea field

### ISSUE THREAD

**Issue by wjt** [Alecaddd/sequeler#354]
## Steps to reproduce:

1. Connect to a PostgreSQL database
2. Execute the following query

```sql
select null :: bytea;
```

## Expected results

A result set is shown with one row and column, with the value blank

## Actual results

```
#0  0x00007ffff704b6db in gda_binary_to_string () at /app/lib/libgda-5.0.so.4
#1  0x00007ffff704b86e in  () at /app/lib/libgda-5.0.so.4
#2  0x00007ffff73cbf65 in g_value_transform () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff73a890b in g_object_setv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff73a98ef in g_object_set_property () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff7951347 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff72a3098 in g_hash_table_foreach () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff795120f in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff7956bdf in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff7bf8525 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff73a0ab6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff73bfb68 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff73c0113 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7952da3 in gtk_cell_area_apply_attributes () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff7b7d488 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff7b8513c in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff7b85633 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff7727fbd in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#18 0x00007ffff72b4c1e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff72b4fd0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff72b5073 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff74d3f25 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x0000555555566d2d in  ()
#23 0x00007ffff6c7e183 in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#24 0x0000555555566bce in  ()
```

I don't know for certain whether this is libgda's fault (probably!) or Sequeler's.

**Comment by Alecaddd** [comment]
Probably LibGDA related.
v6 of that library was just released. I'll test the new version and see what benefits brings, if it fixes this issue, and if it breaks anything else.
